sudo: false
dist: trusty

env:
  global:
  - MAIN=main
script:
  - ./script

jobs:
  include:
    - stage: deploy
      env: TEST_SUITE=none
      install: skip # bundle install is not required
      script: bash ./deploy.sh
